sudo: required
dist: trusty
language: node_js
node_js:
  - 'node'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install -g angular-cli
- npm install -g gulp
- npm install
- ng build

env:
  global:
    - "FTP_USER=dashboard%40mondal.in"
    - "FTP_PASSWORD=6Hr2%5ECqXMD2A6%25qA"

after_success:
  "curl --ftp-create-dirs -T package.json -u $FTP_USER:$FTP_PASSWORD ftp://ftp.mondal.in"